services:
  prod-server:
    build:
      context: .
      target: runner
    env_file:
      - '.env.production'
    ports:
      - 3000:3000
    depends_on:
      postgres:
        condition: service_healthy
    profiles: [prod]

  dev-server:
    build:
      context: .
      target: dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules # Protects container node_modules from host overwrite
    env_file:
      - '.env'
    ports:
      - 3000:3000
    depends_on:
      postgres:
        condition: service_healthy
    profiles: [dev]

  postgres:
    image: postgres:17.4
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: America/Chicago
      PGTZ: America/Chicago
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./logs:/var/log/postgresql
      # - ./certs:/var/lib/postgresql/certs
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U  ${DB_USER} -d ${DB_NAME}']
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    # network_mode: "host"

volumes:
  postgres_data:
