services:
  prod-server:
    build:
      context: .
      target: runner
    env_file:
      - ".env.production"
    ports:
      - 3000:3000
    depends_on:
      postgres:
        condition: service_healthy
    profiles: [prod]

  dev-server:
    build:
      context: .
      target: dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules # Protects container node_modules from host overwrite
    env_file:
      - ".env"
    ports:
      - 3000:3000
    depends_on:
      postgres:
        condition: service_healthy
    profiles: [dev]

  postgres:
    image: postgres:17.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER_FILE: /run/secrets/pg_user
      POSTGRES_DB: voting_db
      POSTGRES_PASSWORD_FILE: /run/secrets/pg_pw
      TZ: America/Chicago
      PGTZ: America/Chicago
    secrets:
      - pg_user
      - pg_pw
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./logs:/var/log/postgresql
      # - ./certs:/var/lib/postgresql/certs
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U $$(cat /run/secrets/pg_user) -d voting_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    # network_mode: "host"

secrets:
  pg_user:
    file: ./secrets/pg_user.txt
  pg_pw:
    file: ./secrets/pg_pw.txt
volumes:
  postgres_data:
